### ISSUE TITLE
base64 response explanation 

### ISSUE THREAD

**Issue by piracypando** [tvg6u56bu5i/ZEFOY#2]
base64 response explanation

**Comment by louissiu198** [comment]
Nice comment, doesn't know how it works, try it in some kind of vps before talking, If I made a logger in, I EAT POOP find me in Dms louissiu#1998

Explain :
this response is from zefoy requests based endpoint "https://zefoy.com" + "/c2VuZC9mb2xeb3dlcnNfdGlrdG9V",
they would encrypt it in base64 and quote them
and even I need to make a logger, i can easily do it in the first few versions
and if you know how to code you would need exec to execute all the encrypted code dumbass
now theres also video proofing its not a logger dumbass try it urself and tell me is it it
